### ISSUE TITLE
Распакуй архив

### ISSUE THREAD

**Issue by rengoyli** [DarkPyDoor/jarvis-new-command#1]
Зачем выкладывать в гитхаб архив вообще? Лучше распакуй архив, чтобы люди видели, к примеру, какие команды ты там добавил.

**Comment by rengoyli** [comment]
Тебе же будет проще, не нужно будет при добавлении новых команд обновлять еще и ридми. 
Запомни на будущее, выкладывать в гитхаб архив - плохо.

**Comment by DarkPyDoor** [comment]
Просто файлов много мне лень было. И я всё равно написал же информацию в Readme.md.

**Comment by rengoyli** [comment]
> Просто файлов много мне лень было. И я всё равно написал же информацию в Readme.md.


Что я написал потом:
> Тебе же будет проще, не нужно будет при добавлении новых команд обновлять еще и ридми.
> Запомни на будущее, выкладывать в гитхаб архив - плохо.

**Comment by DarkPyDoor** [comment]
ну плоха :<
Ладно сделаю позже щас делаю команду музычку :3
